name: Assign project status automatically

inputs:
  PROJECT_ISSUES_TOKEN:
    description: "GH token that has write access to the project board"
    required: true

runs:
  using: composite
  steps:
    - name: Set up env variables
      shell: bash
      run: |
        echo "todo=Todo" >> $GITHUB_ENV
        echo "done=Done" >> $GITHUB_ENV
        echo "in_progress=In Progress" >> $GITHUB_ENV
    - name: Move Engineering issue to ${{ env.todo }}
      if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
      uses: leonsteinhaeuser/project-beta-automations@v2.0.1
      with:
        gh_token: ${{ inputs.PROJECT_ISSUES_TOKEN }}
        organization: owid
        project_id: 4
        resource_node_id: ${{ github.event.issue.node_id }}
        status_value: ${{ env.todo }} # Target status
    - name: Move Engineering issue to ${{ env.done }}
      if: github.event_name == 'issues' && github.event.action == 'closed'
      uses: leonsteinhaeuser/project-beta-automations@v2.0.1
      with:
        gh_token: ${{ inputs.PROJECT_ISSUES_TOKEN }}
        organization: owid
        project_id: 4
        resource_node_id: ${{ github.event.issue.node_id }}
        status_value: ${{ env.done }} # Target status
    - name: Move Engineering PR to ${{ env.in_progress }}
      if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'review_requested')
      uses: leonsteinhaeuser/project-beta-automations@v2.0.1
      with:
        gh_token: ${{ inputs.PROJECT_ISSUES_TOKEN }}
        organization: owid
        project_id: 4
        resource_node_id: ${{ github.event.pull_request.node_id }}
        status_value: ${{ env.in_progress }} # Target status
    - name: Move Engineering PR to ${{ env.done }}
      if: github.event_name == 'pull_request' && github.event.action == 'closed'
      uses: leonsteinhaeuser/project-beta-automations@v2.0.1
      with:
        gh_token: ${{ inputs.PROJECT_ISSUES_TOKEN }}
        organization: owid
        project_id: 4
        resource_node_id: ${{ github.event.pull_request.node_id }}
        status_value: ${{ env.done }} # Target status
    - name: Move Overview issue to ${{ env.todo }}
      if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
      uses: leonsteinhaeuser/project-beta-automations@v2.0.1
      with:
        gh_token: ${{ inputs.PROJECT_ISSUES_TOKEN }}
        organization: owid
        project_id: 6
        resource_node_id: ${{ github.event.issue.node_id }}
        status_value: ${{ env.todo }} # Target status
    - name: Move Overview issue to ${{ env.done }}
      if: github.event_name == 'issues' && github.event.action == 'closed'
      uses: leonsteinhaeuser/project-beta-automations@v2.0.1
      with:
        gh_token: ${{ inputs.PROJECT_ISSUES_TOKEN }}
        organization: owid
        project_id: 6
        resource_node_id: ${{ github.event.issue.node_id }}
        status_value: ${{ env.done }} # Target status
