name: Assign project status automatically

inputs:
  PROJECT_ISSUES_TOKEN:
    description: "GH token that has write access to the project board"
    required: true
  PROJECT_ID:
    description: "Project ID number"
    required: false
    default: "4"
  STATUS_TODO:
    description: "Status name for todo items"
    required: false
    default: "Todo"
  STATUS_DONE:
    description: "Status name for done items"
    required: false
    default: "Done"
  STATUS_IN_PROGRESS:
    description: "Status name for in progress items"
    required: false
    default: "In Progress"
  STATUS_BLOCKED:
    description: "Status name for blocked items"
    required: false
    default: "Blocked"

runs:
  using: composite
  steps:
    - name: Set up env variables
      shell: bash
      run: |
        echo "todo=${{ inputs.STATUS_TODO }}" >> $GITHUB_ENV
        echo "done=${{ inputs.STATUS_DONE }}" >> $GITHUB_ENV
        echo "in_progress=${{ inputs.STATUS_IN_PROGRESS }}" >> $GITHUB_ENV
        echo "blocked=${{ inputs.STATUS_BLOCKED }}" >> $GITHUB_ENV
    - name: Move issue to ${{ env.todo }}
      if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
      uses: leonsteinhaeuser/project-beta-automations@v2.1.0
      with:
        gh_token: ${{ inputs.PROJECT_ISSUES_TOKEN }}
        organization: owid
        project_id: ${{ inputs.PROJECT_ID }}
        resource_node_id: ${{ github.event.issue.node_id }}
        status_value: ${{ env.todo }} # Target status
    - name: Move issue to ${{ env.done }}
      if: github.event_name == 'issues' && github.event.action == 'closed'
      uses: leonsteinhaeuser/project-beta-automations@v2.1.0
      with:
        gh_token: ${{ inputs.PROJECT_ISSUES_TOKEN }}
        organization: owid
        project_id: ${{ inputs.PROJECT_ID }}
        resource_node_id: ${{ github.event.issue.node_id }}
        status_value: ${{ env.done }} # Target status
    - name: Move PR to ${{ env.in_progress }} and current cycle
      if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened')
      uses: leonsteinhaeuser/project-beta-automations@v2.1.0
      with:
        gh_token: ${{ inputs.PROJECT_ISSUES_TOKEN }}
        organization: owid
        project_id: ${{ inputs.PROJECT_ID }}
        resource_node_id: ${{ github.event.pull_request.node_id }}
        status_value: ${{ env.in_progress }} # Target status
        custom_field_values: '[{\"name\": \"Cycle\",\"type\": \"iteration\",\"value\": \"@current\"}]'
    - name: Move PR to ${{ env.blocked }} and current cycle
      if: github.event_name == 'pull_request' && github.event.action == 'review_requested'
      uses: leonsteinhaeuser/project-beta-automations@v2.1.0
      with:
        gh_token: ${{ inputs.PROJECT_ISSUES_TOKEN }}
        organization: owid
        project_id: ${{ inputs.PROJECT_ID }}
        resource_node_id: ${{ github.event.pull_request.node_id }}
        status_value: ${{ env.blocked }} # Target status
        custom_field_values: '[{\"name\": \"Cycle\",\"type\": \"iteration\",\"value\": \"@current\"}]'
    - name: Move PR to ${{ env.done }}
      if: github.event_name == 'pull_request' && github.event.action == 'closed'
      uses: leonsteinhaeuser/project-beta-automations@v2.1.0
      with:
        gh_token: ${{ inputs.PROJECT_ISSUES_TOKEN }}
        organization: owid
        project_id: ${{ inputs.PROJECT_ID }}
        resource_node_id: ${{ github.event.pull_request.node_id }}
        status_value: ${{ env.done }} # Target status
