name: Assign priority based on label

inputs:
  PROJECT_ISSUES_TOKEN:
    description: "GH token that has write access to the project board"
    required: true

runs:
  using: composite
  steps:
    - name: Set up env variables
      shell: bash
      run: |
        echo "prio1=1 - essential" >> $GITHUB_ENV
        echo "prio2=2 - important" >> $GITHUB_ENV
        echo "prio3=3 - nice to have" >> $GITHUB_ENV
        echo 'custom_field_value=[{{\"name\": \"Priority\",\"type\": \"single_select\",\"value\": \"{0}\"}}]' >> $GITHUB_ENV
    - name: Assign priority 1
      uses: leonsteinhaeuser/project-beta-automations@v1.2.1
      if: github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'priority 1 - essential')
      with:
        gh_token: ${{ inputs.PROJECT_ISSUES_TOKEN }}
        organization: owid
        project_id: 4
        resource_node_id: ${{ github.event.issue.node_id }}
        operation_mode: custom_field
        custom_field_values: ${{ format(env.custom_field_value, env.prio1) }}
    - name: Assign priority 2
      uses: leonsteinhaeuser/project-beta-automations@v1.2.1
      if: github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'priority 2 - important')
      with:
        gh_token: ${{ inputs.PROJECT_ISSUES_TOKEN }}
        organization: owid
        project_id: 4
        resource_node_id: ${{ github.event.issue.node_id }}
        operation_mode: custom_field
        custom_field_values: ${{ format(env.custom_field_value, env.prio2) }}
    - name: Assign priority 3
      uses: leonsteinhaeuser/project-beta-automations@v1.2.1
      if: github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'priority 3 - nice to have')
      with:
        gh_token: ${{ inputs.PROJECT_ISSUES_TOKEN }}
        organization: owid
        project_id: 4
        resource_node_id: ${{ github.event.issue.node_id }}
        operation_mode: custom_field
        custom_field_values: ${{ format(env.custom_field_value, env.prio3) }}
    - name: Assign priority none
      uses: leonsteinhaeuser/project-beta-automations@v1.2.1
      if: github.event_name == 'issues' && !contains(github.event.issue.labels.*.name, 'priority 1 - essential') && !contains(github.event.issue.labels.*.name, 'priority 2 - important') && !contains(github.event.issue.labels.*.name, 'priority 3 - nice to have')
      with:
        gh_token: ${{ inputs.PROJECT_ISSUES_TOKEN }}
        organization: owid
        project_id: 4
        resource_node_id: ${{ github.event.issue.node_id }}
        operation_mode: custom_field
        custom_field_values: ${{ format(env.custom_field_value, '') }}
