name: Assign priority based on label

env:
  prio1: "1 - essential"
  prio2: "2 - important"
  prio3: "3 - nice to have"
  custom_field_value: '[{{\"name\": \"Priority\",\"type\": \"single_select\",\"value\": \"{0}\"}}]'

runs:
  using: composite
  name: Sync issue priority to project board
  runs-on: ubuntu-latest
  steps:
    - name: Assign priority 1
      uses: leonsteinhaeuser/project-beta-automations@v1.2.1
      if: github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'priority 1 - essential')
      with:
        gh_token: ${{ secrets.PROJECT_ISSUES_TOKEN }}
        organization: owid
        project_id: 4
        resource_node_id: ${{ github.event.issue.node_id }}
        operation_mode: custom_field
        custom_field_values: ${{ format(env.custom_field_value, env.prio1) }}
    - name: Assign priority 2
      uses: leonsteinhaeuser/project-beta-automations@v1.2.1
      if: github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'priority 2 - important')
      with:
        gh_token: ${{ secrets.PROJECT_ISSUES_TOKEN }}
        organization: owid
        project_id: 4
        resource_node_id: ${{ github.event.issue.node_id }}
        operation_mode: custom_field
        custom_field_values: ${{ format(env.custom_field_value, env.prio2) }}
    - name: Assign priority 3
      uses: leonsteinhaeuser/project-beta-automations@v1.2.1
      if: github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'priority 3 - nice to have')
      with:
        gh_token: ${{ secrets.PROJECT_ISSUES_TOKEN }}
        organization: owid
        project_id: 4
        resource_node_id: ${{ github.event.issue.node_id }}
        operation_mode: custom_field
        custom_field_values: ${{ format(env.custom_field_value, env.prio3) }}
    - name: Assign priority none
      uses: leonsteinhaeuser/project-beta-automations@v1.2.1
      if: github.event_name == 'issues' && !contains(github.event.issue.labels.*.name, 'priority 1 - essential') && !contains(github.event.issue.labels.*.name, 'priority 2 - important') && !contains(github.event.issue.labels.*.name, 'priority 3 - nice to have')
      with:
        gh_token: ${{ secrets.PROJECT_ISSUES_TOKEN }}
        organization: owid
        project_id: 4
        resource_node_id: ${{ github.event.issue.node_id }}
        operation_mode: custom_field
        custom_field_values: ${{ format(env.custom_field_value, '') }}
